-- MySQL Script generated by MySQL Workbench
-- 09/21/16 11:03:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`directores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`directores` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peliculas` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `genero` VARCHAR(100) NULL,
  `duracion` INT NULL,
  `directores_id` INT NOT NULL,
  PRIMARY KEY (`id`, `directores_id`),
  INDEX `fk_peliculas_directores_idx` (`directores_id` ASC),
  CONSTRAINT `fk_peliculas_directores`
    FOREIGN KEY (`directores_id`)
    REFERENCES `mydb`.`directores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actores` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cintas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cintas` (
  `id` INT NOT NULL,
  `numero_copia` INT NULL,
  `peliculas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cintas_peliculas1_idx` (`peliculas_id` ASC),
  CONSTRAINT `fk_cintas_peliculas1`
    FOREIGN KEY (`peliculas_id`)
    REFERENCES `mydb`.`peliculas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`socios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fichas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fichas` (
  `id` INT NOT NULL,
  `fecha_prestamo` DATETIME NULL,
  `socios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fichas_socios1_idx` (`socios_id` ASC),
  CONSTRAINT `fk_fichas_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`listas` (
  `id` INT NOT NULL,
  `fecha` DATETIME NULL,
  `estatus` VARCHAR(45) NULL,
  `peliculas_id` INT NOT NULL,
  `socios_id` INT NOT NULL,
  `hora` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_listas_peliculas1_idx` (`peliculas_id` ASC),
  INDEX `fk_listas_socios1_idx` (`socios_id` ASC),
  CONSTRAINT `fk_listas_peliculas1`
    FOREIGN KEY (`peliculas_id`)
    REFERENCES `mydb`.`peliculas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listas_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actores_has_peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actores_has_peliculas` (
  `actores_id` INT NOT NULL,
  `peliculas_id` INT NOT NULL,
  PRIMARY KEY (`actores_id`, `peliculas_id`),
  INDEX `fk_actores_has_peliculas_peliculas1_idx` (`peliculas_id` ASC),
  INDEX `fk_actores_has_peliculas_actores1_idx` (`actores_id` ASC),
  CONSTRAINT `fk_actores_has_peliculas_actores1`
    FOREIGN KEY (`actores_id`)
    REFERENCES `mydb`.`actores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actores_has_peliculas_peliculas1`
    FOREIGN KEY (`peliculas_id`)
    REFERENCES `mydb`.`peliculas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cintas_has_fichas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cintas_has_fichas` (
  `cintas_id` INT NOT NULL,
  `fichas_id` INT NOT NULL,
  `fecha_entrega` DATE NULL,
  `estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`cintas_id`, `fichas_id`),
  INDEX `fk_cintas_has_fichas_fichas1_idx` (`fichas_id` ASC),
  INDEX `fk_cintas_has_fichas_cintas1_idx` (`cintas_id` ASC),
  CONSTRAINT `fk_cintas_has_fichas_cintas1`
    FOREIGN KEY (`cintas_id`)
    REFERENCES `mydb`.`cintas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cintas_has_fichas_fichas1`
    FOREIGN KEY (`fichas_id`)
    REFERENCES `mydb`.`fichas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`directores_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`directores_has_socios` (
  `directores_id` INT NOT NULL,
  `socios_id` INT NOT NULL,
  PRIMARY KEY (`directores_id`, `socios_id`),
  INDEX `fk_directores_has_socios_socios1_idx` (`socios_id` ASC),
  INDEX `fk_directores_has_socios_directores1_idx` (`directores_id` ASC),
  CONSTRAINT `fk_directores_has_socios_directores1`
    FOREIGN KEY (`directores_id`)
    REFERENCES `mydb`.`directores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_directores_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actores_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actores_has_socios` (
  `actores_id` INT NOT NULL,
  `socios_id` INT NOT NULL,
  PRIMARY KEY (`actores_id`, `socios_id`),
  INDEX `fk_actores_has_socios_socios1_idx` (`socios_id` ASC),
  INDEX `fk_actores_has_socios_actores1_idx` (`actores_id` ASC),
  CONSTRAINT `fk_actores_has_socios_actores1`
    FOREIGN KEY (`actores_id`)
    REFERENCES `mydb`.`actores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actores_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
